sales_dw:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '3306') | int }}"
      schema: "{{ env_var('DB_NAME', 'sales_dw') }}"
      username: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      ssl_disabled: true
